name             'custom_apache'
maintainer       'Denis'
maintainer_email 'kbpsec@gmail.com'
license          'Apache-2.0'
description      'Installs/Configures custom_apache'
long_description 'Installs/Configures custom_apache'
version          '0.2.0'
supports 	 'centos'
issues_url 'https://github.com/learn-chef/custom_apache/issues'
source_url 'https://github.com/learn-chef/custom_apache'
chef_version '>= 12.7' if respond_to?(:chef_version)
